# Generated by Django 2.1.2 on 2018-10-30 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SensorsTable',
            fields=[
                ('sensor_uuid', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('sensor_desc', models.CharField(max_length=256)),
                ('sensor_mid', models.CharField(max_length=256)),
                ('gw_uuid', models.CharField(blank=True, max_length=32, null=True)),
                ('sensor_loc_lat', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('sensor_loc_long', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('sensor_loc_blg', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_loc_room', models.CharField(blank=True, max_length=100, null=True)),
                ('sensor_loc_position', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'sensors_table',
                'managed': False,
            },
        ),
    ]
