# Generated by Django 2.1.2 on 2018-10-31 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0002_category_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=30, unique=True)),
                ('fees', models.IntegerField()),
                ('rating', models.IntegerField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.category')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_app.location')),
            ],
        ),
    ]
