# Generated by Django 2.1.2 on 2018-11-16 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0004_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 16, 18, 0, 55, 391878)),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='doc_name',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='fees',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='rating',
            field=models.IntegerField(null=True),
        ),
    ]
