# Generated by Django 2.1.2 on 2018-11-17 06:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0005_auto_20181116_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='slot',
            field=models.CharField(default='slot1', max_length=6),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 12, 10, 52, 526094)),
        ),
    ]
