# Generated by Django 2.1.2 on 2018-11-17 07:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first_app', '0006_auto_20181117_1210'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='slot',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='date',
            field=models.DateField(default=datetime.datetime(2018, 11, 17, 12, 34, 53, 336280)),
        ),
    ]
